# Nome do projeto
spring.application.name=filmes-api

# Porta onde o backend vai rodar (idêntica à baseURL do seu arquivo api.js)
server.port=8080

# Configuração da conexão com o Banco de Dados H2 em memória
spring.datasource.url=jdbc:h2:mem:filmesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa o Console Visual do H2 no navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true